### PR TITLE
Python3

### PR DESCRIPTION
**Pull request by busla**
First shot at porting to Python3.

### CODE REVIEW

**Comment by busla** [comment]
icekey auth not tested.

**Comment by busla** [comment]
fake-auth now working.

**Comment by busla** [comment]
Django 1.9 support.. jei!

**Comment by jamesrobb** [comment]
Is there a staging environment I can see this in action? This seems like a pretty big change to the project.

**Comment by busla** [comment]
I´ll try to push to staging tomorrow. I´m sure there will be some minor issues with staticfile urls since I haven´t tested the {{static_url}} to {% static 'mytemplate' %} migration.

I didn´t do any cleanup either so there are still deprecated calls all over the place but my terminal is clean of warnings :-)

**Comment by jamesrobb** [comment]
I would make sure you are solid on all those issues. The idea is that the master branch is solid.

**Comment by busla** [comment]
merge it in to a python3 branch perhaps?

**Comment by busla** [comment]
merging the PR to the original repo is actually not of any importance right now. Let´s take a look at this when the voting-cart is done (https://github.com/busla/safetyvalve/tree/feature/voting-cart) and merged into the python3 branch.

**Comment by jamesrobb** [comment]
I think the idea of a voting card merits a conclusion before throwing development resources at it.

**Comment by busla** [comment]
Sounds good. What are your initial thoughts on this?

A basic implementation is almost done on the feature branch so I´ll finish it atleast.

**Comment by busla** [comment]
@jamesrobb @helgihg looks pretty stable now. Did more cleanup and removed a few commits that were part of the voting-cart.

**Comment by jamesrobb** [comment]
Closing this since its been 4 years.

**Pull request closed without merging**
